eldar/apps/blog/urls.py
from django.urls import path
from .views import home, news


app_name = 'blog'

urlpatterns = [
    path('', home, name='home'),
    path('news/<int:title_id>/', news, name='news')
]

eldar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eldar.apps.echen.urls')),
    path('r/', include('eldar.apps.repeat.urls')),
    path('ue/', include('eldar.apps.Ueconomics.urls')),
    path('c/', include('eldar.apps.core.urls')),
    path('d/', include('eldar.apps.dataAnalysis.urls')),
    path('t/', include('eldar.apps.tabs.urls')),
    path('b/', include('eldar.apps.brenda.urls')),
    path('cs/', include('eldar.apps.county.urls')),
    path('bt/', include('eldar.apps.buttons.urls')),
    path('ct/', include('eldar.apps.cities.urls')),
    path('blog/', include('eldar.apps.blog.urls')),
    path('h/', include('eldar.apps.hangman.urls')),
    path('posts/', include('eldar.apps.posts.urls')),

]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eldar/apps/blog/models.py
from django.db import models


class Languages(models.Model):
    lang_name = models.CharField(max_length=30)

    def __str__(self):
        return self.lang_name

class Topic(models.Model):
    title = models.CharField(max_length=30)
    text = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    lang = models.ForeignKey(Languages, null=True,  on_delete=models.CASCADE, related_name='topic')

    def __str__(self):
        return self.title


class News(models.Model):
    title = models.ForeignKey(Topic, null=True, on_delete=models.CASCADE, related_name='news_title')
    image = models.ImageField(upload_to='blog/')
    text = models.TextField(max_length=5000)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)


class Comments(models.Model):
    name = models.CharField(max_length=50)
    message = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey(News, null=True, on_delete=models.CASCADE, related_name='news_title')

    def __str__(self):
        return str(self.name)

eldar/apps/blog/views.py
from django.shortcuts import render, redirect
from  .models import News, Languages, Topic, Comments

def home(request):
   lang = Languages.objects.all()
   return render(request, 'blog/index.html', {'lang': lang})


def news(request, title_id):
   news = Topic.objects.get(id=title_id)
   title = News.objects.get(title=news)


   if request.method == 'POST':
      name = request.POST['fname']
      comment_ = request.POST['message']
      Comments.objects.create(name=name, message=comment_, news=title)

      return redirect('blog:news', title_id)

   comment = Comments.objects.filter(news=title)
   #print(comment)


   return render(request, 'blog/news.html', {'news': news, 'title': title, 'comment':comment})

eldar/apps/blog/templates/blog/index.html
{% extends 'base_blog.html' %}

eldar/apps/blog/templates/blog/news.html
{% extends 'base_blog.html' %}
{% load thumbnail %}


    {% block title %}
    <title>SINGLE_POST</title>
    {% endblock title %}

 {% block links %}
    <li><a href="{% url 'blog:home'%}" style="text-decoration:none; color:green">Blog</a></li>
    <li>Single Post</li>
 {% endblock links %}

{% block head %}

{% endblock head %}


{% block body %}
  <div class="para">

    <h2>Js {{title.title}}</h2>
      {% thumbnail title.image "5000x2000" crop as ci %}
      <img src="{{ci.url}}" width="250px" height="150px">
      <p>{{title.text|safe}}</p>
  </div>
  <form method="POST" action="">
      {% csrf_token %}
      Name:
      <br>
      <input type="text" name="fname" size="30">
      <br><br>
      Message:
      <br>
      <textarea rows="10" cols="40" name="message"></textarea>
      <br><br>
      <input type="submit" value="submit">
  </form>
<br><br>
{% for comment in comment %}
{{comment.message}}<br>
{% endfor %}

<hr class="line2">
<div class="copyright">
    <h4>© ASIO BRENDA</h4>
  </div>

{% endblock body %}