eldar/apps/Ueconomics/urls.py
from django.urls import path
from .views import home, tabs,get_data

app_name = 'Ueconomics'

urlpatterns = [
    path('', home, name='home'),
    path('tabs/', tabs, name='Tabs'),
    path('get_data/', get_data, name='Get_data'),
    #path('delete_data/', delete_data, name='Delete'),

]

eldar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eldar.apps.echen.urls')),
    path('r/', include('eldar.apps.repeat.urls')),
    path('ue/', include('eldar.apps.Ueconomics.urls')),
    path('c/', include('eldar.apps.core.urls')),
    path('d/', include('eldar.apps.dataAnalysis.urls')),
    path('t/', include('eldar.apps.tabs.urls')),
    path('b/', include('eldar.apps.brenda.urls')),
    path('cs/', include('eldar.apps.county.urls')),
    path('bt/', include('eldar.apps.buttons.urls')),
    path('ct/', include('eldar.apps.cities.urls')),
    path('blog/', include('eldar.apps.blog.urls')),
    path('h/', include('eldar.apps.hangman.urls')),
    path('posts/', include('eldar.apps.posts.urls')),

]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eldar/apps/Ueconomics/models.py
from django.db import models

class Source(models.Model):
    class Meta:
        verbose_name_plural = ('Source')
        ordering = ['id']

    type = models.CharField(max_length=100, blank=True, null=False)

    def __str__(self):
        return self.type

class Product(models.Model):
    class Meta:
        verbose_name_plural = ('Product')
        ordering = ['id']


    sitc2 = models.PositiveIntegerField(null=False, blank=True)
    description = models.CharField(max_length=200, blank=True, null=False)

    def __str__(self):
        return str(self.sitc2) + str(self.description)

class YearData(models.Model):
    class Meta:
        verbose_name_plural = ('YearData')
        ordering = ['id']


    source = models.ForeignKey(Source, null=False, on_delete=models.CASCADE, related_name='source_type')
    product = models.ForeignKey(Product, null=False, on_delete=models.CASCADE, related_name='product')
    year = models.BigIntegerField(default=0, null=False, blank=True)
    value = models.BigIntegerField(default=0, null=False, blank=True)

    def __str__(self):
        return str(self.source.id) + str(self.product.id) + str(self.year) + str(self.value)


class Cities(models.Model):
    class Meta:
        verbose_name_plural = ('Cities')

    name = models.CharField(max_length=500)
    color = models.CharField(max_length=300)
    description = models.CharField(max_length=600)

    def __str__(self):
        return self.name + self.color + self.description

eldar/apps/Ueconomics/views.py
from django.shortcuts import render
from .models import Cities
from django.db import IntegrityError
from django.http import JsonResponse, HttpResponseBadRequest




def home(request):
    cities_ = "Welcome to Cities"


    return render(request, 'Ueconomics/index.html', {'cities': cities_})


def tabs(request):
    tab_name_ = request.POST['dic']
    dic_ = eval(tab_name_)
    name = dic_['cityName']
    description = dic_['description']
    color = dic_['color']
    c, t = Cities.objects.get_or_create(name=name, description=description, color=color)
    print(t)
    print(c.id)
    print(c)
    dic = {
        'tab_id': c.id,
        'name': c.name,
        'description': c.description,
        'color': c.color
    }
    print('---'*10)
    #print(dic)
    return JsonResponse(dic)

def get_data(request):

    content = Cities.objects.all()
    #print(content)
    dic = {}

    for c in content:
        dic[c.id] = {'city_name': c.name, 'description': c.description, 'color': c.color}
        #print(dic)
    return JsonResponse(dic)

eldar/apps/Ueconomics/templates/Ueconomics/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static  'ueconomics/style.css' %}">
    <link href="{% static 'styling/cities.css'%}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>


    <title>Title</title>
</head>
<body>
 <h1 style="text-align: center; color:red; margin-top:70px">{{varx}}</h1>

 <br>
<button  style="cursor:pointer" onclick="addTab(event)" id="url" data_path="{% url 'Ueconomics:Tabs' %}">Add tab</button>
 <button  style="cursor:pointer" onclick="deleteTab(event)">Delete tab</button>
<br>
<br>
 <div class="tab" id="tab_container" url_path="{% url 'Ueconomics:Get_data' %}">
</div>


<div id="content_id">
</div>

 <p id="demo"></p>
<script src="{% static 'js/js.cookie.min.js' %}"></script>
<script src="{% static 'js/cities1.js' %}"></script>
<script type="text/javascript">

     var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
              // these HTTP methods do not require CSRF protection
              return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
              }
            });

  $(document).ready(function () {
        get_data()
  });
    </script>

</body>
</html>

eldar/apps/Ueconomics/templates/Ueconomics/load_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>{{varx}}</h1>
</body>
</html>