eldar/apps/echen/urls.py
from django.urls import path
from .views import ClientView, CreateClient, ViewClient, UpdateClient


app_name = 'echen'

urlpatterns = [
    path('', ClientView.as_view(), name='Home'),
    path('Createclient/', CreateClient.as_view(), name='create-client'),
    path('Detailclient/<int:pk>', ViewClient.as_view(), name='detail-client'),
    path('Updateclient/<int:pk>', UpdateClient.as_view(), name='update-client'),


]

eldar/apps/repeat/urls.py
from django.urls import path
from .views import (home, tables, addmember, view_member, update_member, get_author, district, upload_data)


app_name = 'repeat'

urlpatterns = [
    path('', home, name='Repeat'),
    path('tables/', tables, name='Tables'),
    path('Newmember/', addmember, name='newmember'),
    path('Viewmember/<int:pk>', view_member, name='view-member'),
    path('Updatemember/<int:pk>', update_member, name='update-member'),
    path('author/<int:author_id>', get_author, name='author'),
    path('district/', district, name='district'),
    path('loaddata/', upload_data, name='loaddata'),
]

eldar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eldar.apps.echen.urls')),
    path('r/', include('eldar.apps.repeat.urls')),
    path('ue/', include('eldar.apps.Ueconomics.urls')),
    path('c/', include('eldar.apps.core.urls')),
    path('d/', include('eldar.apps.dataAnalysis.urls')),
    path('t/', include('eldar.apps.tabs.urls')),
    path('b/', include('eldar.apps.brenda.urls')),
    path('cs/', include('eldar.apps.county.urls')),
    path('bt/', include('eldar.apps.buttons.urls')),
    path('ct/', include('eldar.apps.cities.urls')),
    path('blog/', include('eldar.apps.blog.urls')),
    path('h/', include('eldar.apps.hangman.urls')),
    path('posts/', include('eldar.apps.posts.urls')),

]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eldar/apps/echen/models.py
from django.db import models

class Client(models.Model):

      class Meta:
            verbose_name_plural = ('Client')
            ordering = ['id']

      name = models.CharField(max_length=100, blank=True, null=False)
      description = models.TextField(max_length=300, blank=True, null=False)
      image = models.ImageField(upload_to='client_images/', blank=True, null=False)

      def __str__(self):
            return self.name

eldar/apps/echen/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from.models import Client
from django.views.generic import ListView, CreateView, DetailView, UpdateView


class ClientView(ListView):
    model = Client
    template_name = 'echen/index.html'
    context_object_name = 'client'


class CreateClient(CreateView):
      model = Client
      template_name = 'echen/create_client.html'
      fields = ['name', 'description', 'image']
      success_url = reverse_lazy('echen:Home')


class ViewClient(DetailView):
      model = Client
      template_name = 'echen/detail_client.html'


class UpdateClient(UpdateView):
    model = Client
    template_name = 'echen/update_client.html'
    fields = ['name', 'description', 'image']
    success_url = reverse_lazy('echen:Home')

eldar/apps/echen/templates/echen/create_client.html
{% extends 'base_echen.html' %}

{% load static %}

{% block title %}
<title>ECHEN1</title>
{% endblock title %}

{% block toolbar %}
 <a class="active">Home</a>
 <a href="{% url 'repeat:Repeat' %}">Repeat</a>
{% endblock toolbar %}


{% block body %}
 <h1>CREATE CLIENT</h1>

<br>
<br>
<form method="POST" enctype="multipart/form-data">
 {% csrf_token %}

 {{form.as_p}}
<button>SUBMIT</button>
</form>



{% endblock body %}

eldar/apps/echen/templates/echen/detail_client.html
{% extends 'base_echen.html' %}

{% load static %}

{% block title %}
<title>ECHEN1</title>
{% endblock title %}

{% load thumbnail %}

{% block toolbar %}
 <a class="active">Home</a>
 <a href="{% url 'repeat:Repeat' %}">Repeat</a>
{% endblock toolbar %}


{% block body %}
 <h1>CREATE CLIENT</h1>

<br>
<br>
<table>
<h1>Client Details</h1>
<tr>
<th>ID:</th>
<td>{{object.id}}</td>
<tr>
 <br>
 <br>
 <tr>
<th>NAME:</th>
<td>{{object.name}}</td>
<tr>
 <br>
 <br>
 <tr>
<th>DESCRIPTION:</th>
<td>{{object.description}}</td>
<tr>
 <br>
 <br>
 <tr>
<th>IMAGE:</th>
<td>
 {% thumbnail object.image "5000x2000" crop as ci %}
 <img src="{{ci.url}}" width="250px" height="150px">
</td>
<tr>
<!-- Other fields -->
</table>

<a href="{% url 'echen:Home' %}">back</a>


{% endblock body %}

eldar/apps/echen/templates/echen/index.html
{% extends 'base_echen.html' %}

{% load thumbnail %}

{% load static %}

{% block title %}
<title>ECHEN1</title>
{% endblock title %}

{% block toolbar %}
 <a class="active">Home</a>
 <a href="{% url 'repeat:Repeat' %}">Repeat</a>
{% endblock toolbar %}


{% block links %}
 <link href="{% static 'styling/table1.css' %}"   rel="stylesheet">
{% endblock links %}

{% block body %}
 <h1>WELCOME TO MY HOME PAGE, html</h1>
<br>
<br>
<br>
<button>
        <a href="{% url 'echen:create-client' %}">Add client</a>
</button>
<br>
<br>
<table>
 <tr>
  <th>ID</th>
  <th>NAME</th>
  <th>DESCRIPTION</th>
  <th>IMAGE</th>
  <th>VIEW</th>
  <th>UPDATE</th>
 </tr>

{% for c in client %}
<tr>
<td>{{c.id}}</td>
<td>{{c.name}}</td>
<td>{{c.description}}</td>
<td>
 {% thumbnail c.image "5000x2000" crop as ci %}
 <img src="{{ci.url}}" width="250px" height="150px">
</td>
 <td>
  <a href="{% url 'echen:detail-client' c.id %}">VIEWS</a>
 </td>
 <td>
  <a href="{% url 'echen:update-client' c.id %}">Update</a>
 </td>
</tr>
{% endfor %}

</table>
{% endblock body %}

eldar/apps/echen/templates/echen/update_client.html
{% extends 'base_echen.html' %}

{% load static %}

{% block title %}
<title>ECHEN1</title>
{% endblock title %}

{% block toolbar %}
 <a class="active">Home</a>
 <a href="{% url 'repeat:Repeat' %}">Repeat</a>
{% endblock toolbar %}


{% block body %}
 <h1>CREATE CLIENT</h1>

<br>
<br>
<form method="POST" enctype="multipart/form-data">
 {% csrf_token %}

 {{form.as_p}}
<button>SUBMIT</button>
</form>



{% endblock body %}