eldar/apps/tabs/urls.py
from django.urls import path
from .views import home, tabs, get_data, delete_data, save_content, save_btn, saved_btn

app_name = 'tabs'

urlpatterns = [
    path('', home, name='Home'),
    path('add_tab/', tabs, name='add_tab'),
    path('get_data/', get_data, name='get_data'),
    path('delete_tab/', delete_data, name='delete_tab'),
    path('save_content/', save_content, name='saveContent'),
    path('save_btn/', save_btn, name='save_btn'),
    path('saved_btn/', saved_btn, name='saved_btn'),

]

eldar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eldar.apps.echen.urls')),
    path('r/', include('eldar.apps.repeat.urls')),
    path('ue/', include('eldar.apps.Ueconomics.urls')),
    path('c/', include('eldar.apps.core.urls')),
    path('d/', include('eldar.apps.dataAnalysis.urls')),
    path('t/', include('eldar.apps.tabs.urls')),
    path('b/', include('eldar.apps.brenda.urls')),
    path('cs/', include('eldar.apps.county.urls')),
    path('bt/', include('eldar.apps.buttons.urls')),
    path('ct/', include('eldar.apps.cities.urls')),
    path('blog/', include('eldar.apps.blog.urls')),
    path('h/', include('eldar.apps.hangman.urls')),
    path('posts/', include('eldar.apps.posts.urls')),

]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eldar/apps/tabs/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField

class City(models.Model):
    class Meta:
        verbose_name_plural = ('City')

    city_name = models.CharField(max_length=500)
    color = models.CharField(max_length=300)
    description = models.CharField(max_length=600)
    save_btn = JSONField(null=True)

    def __str__(self):
        return self.color + self.description


class Client(models.Model):
    class Meta:
        verbose_name_plural = ('Client')

    name = models.CharField(max_length=500)
    gender = models.CharField(max_length=300)

    def __str__(self):
        return self.name + self.gender

eldar/apps/tabs/views.py
from django.shortcuts import render
from .models import City, Client
from django.http import JsonResponse


def home(request):
    varx = 'CREATING HTML ELEMENTS USING JAVASCRIPT'

    tab = City.objects.all()

    # if request.method == 'POST':
    #     name_ = request.POST['name']
    #     gender_ = request.POST['gender']
    #
    #     Client.objects.create(name=name_, gender=gender_)

    return render(request, 'tabs/index.html', {'varx': varx, 'tabs':tab})




def tabs(request):
    tab_name = request.POST['dic_']
    #print('type is_', type(tab_name))

    print(type(tab_name))
    dic__ = eval(tab_name)
    print('-----' *20)
    print("type_of_dic_is_", type(dic__))
    name = dic__['city_name']
    color_ = dic__['color']
    description_ = dic__['description']
    tab_name, t = City.objects.get_or_create(city_name=name, color=color_, description=description_)
    print(tab_name.city_name)
    print(tab_name.id)
    dic = {
      'tab_id': tab_name.id,
        'tab_name': tab_name.city_name,
        'tab_content':tab_name.description,
        'tab_color': tab_name.color,
    }

    return JsonResponse(dic)


def get_data(request):
    content = City.objects.all()
    #print(content)
    dic = {}

    for c in content:
        dic[c.id] = {'city_name': c.city_name, 'tab_color': c.color,'tab_content':c.description}
        #print('----'*20)
        #print(dic)
    return JsonResponse(dic)

def delete_data(request):
    delete_content = request.POST['delete_tab_']
    content = City.objects.get(city_name=delete_content)
    tab_id = content.id
    content.delete()
    dic = {
         'tab_id_':tab_id

    }
    return JsonResponse(dic)

def save_content(request):
    tab_id = request.POST['tab_id']
    #print(tab_id)
    content = request.POST['dic_']
    #print(content)
    tab = City.objects.get(id=tab_id)
    tab.description = content
    #print(111111)
    #print(tab.description)
    tab.save()

    dic = {
        'tab_id':tab_id
    }

    return JsonResponse(dic)

def save_btn(request):
    tab_id = request.POST.get('tab_num')
    btn_id = request.POST.get('btn_id')
    tab_name_ = request.POST.get('tab_name')
    save_btn_ = request.POST.get('save_btn1_')

    content = {"btn_" + tab_name_: save_btn_, 'btn_id_':btn_id}

    city = City.objects.get(id=tab_id)

    #Retrieve from python the JSON if it's not there initialize to {}
    saved_data = city.save_btn if city.save_btn else {}

    #Ensure that the saved_data[tab_id] is a list
    if tab_id not in saved_data:
        saved_data[tab_id] = []

    #Append the content
    saved_data[tab_id].append(content)

    #Updating the appended content
    city.save_btn = saved_data
    city.save()
    dic = {}

    return JsonResponse(dic)


def saved_btn(request):
    btn_saved = City.objects.all()

    dic = {}

    #print(dic)

    for b in btn_saved:
        dic[b.id] = b.save_btn

    dic = {'saved_btn': dic}

    #print('--'*40)
    #print(dic)

    return JsonResponse(dic)

eldar/apps/tabs/templates/tabs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static  'tabs/styles/tab.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <title>Title</title>
</head>
<body id="demo">
 <h1 style="text-align: center; color:red; margin-top:70px">{{varx}}</h1>
<div id="content_id">
</div>

<script>
</script>

<script src="{% static 'js/tabs22.js' %}"></script>
<script src="{% static 'js/js.cookie.min.js' %}"></script>
<script type="text/javascript">

     var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
              // these HTTP methods do not require CSRF protection
              return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
              }
            });
    var body_id = document.getElementById('demo');
    var add_tab_url = "{% url 'tabs:add_tab'%}";
    var get_data_ = "{% url 'tabs:get_data'%}";
    var delete_tab = "{% url 'tabs:delete_tab'%}";
    var save_content = "{% url 'tabs:saveContent'%}";
    var save_btn= "{% url 'tabs:save_btn'%}";
    var saved_btn= "{% url 'tabs:saved_btn'%}";
    //alert(save_btn)

    dic = {'body_id_': body_id, 'add_tab_url_': add_tab_url, 'get_data_': get_data_, 'delete_tab_':delete_tab,
    'save_content_':save_content, 'save_btn_': save_btn, 'saved_btn_':saved_btn }
    //alert(111)
    //alert(JSON.stringify(dic))

       $(document).ready(function () {
          var manager = new Admin(dic);
          manager.create_elements(dic);

      });


    </script>



</body>